import GovernanceTokenAbi from '../abi/GovernanceToken';
import MerkleAirdropAbi from '../abi/MerkleAirdrop';
import SimpleDAOAbi from '../abi/SimpleDAO';
import StakingPoolAbi from '../abi/StakingPool';

// ── Addresses ─────────────────────────────────────────────────────────────────

export const GOVERNANCE_TOKEN_ADDRESS =
  (process.env.NEXT_PUBLIC_GOVERNANCE_TOKEN_ADDRESS as `0x${string}`) ??
  '0x0000000000000000000000000000000000000000';

export const STAKING_POOL_ADDRESS =
  (process.env.NEXT_PUBLIC_STAKING_POOL_ADDRESS as `0x${string}`) ??
  '0x0000000000000000000000000000000000000000';

export const MERKLE_AIRDROP_ADDRESS =
  (process.env.NEXT_PUBLIC_MERKLE_AIRDROP_ADDRESS as `0x${string}`) ??
  '0x0000000000000000000000000000000000000000';

export const SIMPLE_DAO_ADDRESS =
  (process.env.NEXT_PUBLIC_SIMPLE_DAO_ADDRESS as `0x${string}`) ??
  '0x0000000000000000000000000000000000000000';

// ── ABIs (generated by scripts/sync-abis.js — run after forge build) ─────────

export const GOVERNANCE_TOKEN_ABI = GovernanceTokenAbi;
export const STAKING_POOL_ABI = StakingPoolAbi;
export const MERKLE_AIRDROP_ABI = MerkleAirdropAbi;
export const SIMPLE_DAO_ABI = SimpleDAOAbi;
